# Generated by Django 3.0 on 2021-09-23 02:26


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='horario_registro',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='registrado_por',
        ),
    ]
